var Name = "Abdul salam";
var text = "this is my first js";
let = id = 665490;
var age = 20;
var stud = "i m a student"
document.getElementById("output1").innerHTML = Name;
document.getElementById("output2").innerHTML = text;
document.getElementById("output3").innerHTML = id;
document.getElementById("output4").innerHTML = age;
document.getElementById("output5").innerHTML =  stud;
output1.style .color = "red"
output3.style .fontfimly = "16"
output2.style .color= "blue"
